cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    elephant_man:
      email: elephant_lover@gmail.com
      id: 952e2eedbd9a013dccd123806bea43a2
      logged_in: false
      name: Andro Shanki
      password: $2b$12$S4Zc5CFYDOSFV9Wi35pOY.qMAzv7f6xQ0g5B4b6DgkzOWzmRPEXTu
    sabhashanki:
      email: test@gmail.com
      id: 62f88833f241ee33f698d895b81c5eff
      logged_in: false
      name: shankesh
      password: $2b$12$YPCeNc397qprTnhI9pXxV.zpxwNT51uvONNKeZoT/.MAEPvVmWmKi
    sabhashankii:
      email: ihave@gmail.com
      id: edba8337ddc986f2c3854f550a75f863
      logged_in: false
      name: shankesh
      password: $2b$12$.xY0iDFhuminsBF5BizNMOplvgztV0mrWEI1Rvx1NIuFwSV8Ij5Tq
    shankesh:
      email: hello@gmail.com
      id: 8d65e32a1c7989ebaf9f83d02011c8c1
      logged_in: false
      name: Shankesh Raju MS
      password: $2b$12$tMEI/n73JIvNEnwDz97wiuBytU3pjpXbRDneVg1W8CVpT6u8lRtvG
preauthorized:
  emails:
  - melsby@gmail.com
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    elephant_man:
      email: elephant_lover@gmail.com
      id: 952e2eedbd9a013dccd123806bea43a2
      logged_in: false
      name: Andro Shanki
      password: $2b$12$S4Zc5CFYDOSFV9Wi35pOY.qMAzv7f6xQ0g5B4b6DgkzOWzmRPEXTu
    sabhashanki:
      email: test@gmail.com
      id: 62f88833f241ee33f698d895b81c5eff
      logged_in: false
      name: shankesh
      password: $2b$12$YPCeNc397qprTnhI9pXxV.zpxwNT51uvONNKeZoT/.MAEPvVmWmKi
    sabhashankii:
      email: ihave@gmail.com
      id: edba8337ddc986f2c3854f550a75f863
      logged_in: false
      name: shankesh
      password: $2b$12$.xY0iDFhuminsBF5BizNMOplvgztV0mrWEI1Rvx1NIuFwSV8Ij5Tq
    shankesh:
      email: hello@gmail.com
      id: 8d65e32a1c7989ebaf9f83d02011c8c1
      logged_in: false
      name: Shankesh Raju MS
      password: $2b$12$tMEI/n73JIvNEnwDz97wiuBytU3pjpXbRDneVg1W8CVpT6u8lRtvG
preauthorized:
  emails:
  - melsby@gmail.com
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    elephant_man:
      email: elephant_lover@gmail.com
      id: 952e2eedbd9a013dccd123806bea43a2
      logged_in: false
      name: Andro Shanki
      password: $2b$12$S4Zc5CFYDOSFV9Wi35pOY.qMAzv7f6xQ0g5B4b6DgkzOWzmRPEXTu
    sabhashanki:
      email: test@gmail.com
      id: 62f88833f241ee33f698d895b81c5eff
      logged_in: false
      name: shankesh
      password: $2b$12$YPCeNc397qprTnhI9pXxV.zpxwNT51uvONNKeZoT/.MAEPvVmWmKi
    sabhashankii:
      email: ihave@gmail.com
      id: edba8337ddc986f2c3854f550a75f863
      logged_in: false
      name: shankesh
      password: $2b$12$.xY0iDFhuminsBF5BizNMOplvgztV0mrWEI1Rvx1NIuFwSV8Ij5Tq
    shankesh:
      email: hello@gmail.com
      id: 8d65e32a1c7989ebaf9f83d02011c8c1
      logged_in: false
      name: Shankesh Raju MS
      password: $2b$12$tMEI/n73JIvNEnwDz97wiuBytU3pjpXbRDneVg1W8CVpT6u8lRtvG
preauthorized:
  emails:
  - melsby@gmail.com
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    elephant_man:
      email: elephant_lover@gmail.com
      id: 952e2eedbd9a013dccd123806bea43a2
      logged_in: false
      name: Andro Shanki
      password: $2b$12$S4Zc5CFYDOSFV9Wi35pOY.qMAzv7f6xQ0g5B4b6DgkzOWzmRPEXTu
    sabhashanki:
      email: test@gmail.com
      id: 62f88833f241ee33f698d895b81c5eff
      logged_in: false
      name: shankesh
      password: $2b$12$YPCeNc397qprTnhI9pXxV.zpxwNT51uvONNKeZoT/.MAEPvVmWmKi
    sabhashankii:
      email: ihave@gmail.com
      id: edba8337ddc986f2c3854f550a75f863
      logged_in: false
      name: shankesh
      password: $2b$12$.xY0iDFhuminsBF5BizNMOplvgztV0mrWEI1Rvx1NIuFwSV8Ij5Tq
    shankesh:
      email: hello@gmail.com
      id: 8d65e32a1c7989ebaf9f83d02011c8c1
      logged_in: false
      name: Shankesh Raju MS
      password: $2b$12$tMEI/n73JIvNEnwDz97wiuBytU3pjpXbRDneVg1W8CVpT6u8lRtvG
preauthorized:
  emails:
  - melsby@gmail.com
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    elephant_man:
      email: elephant_lover@gmail.com
      id: 952e2eedbd9a013dccd123806bea43a2
      logged_in: false
      name: Andro Shanki
      password: $2b$12$S4Zc5CFYDOSFV9Wi35pOY.qMAzv7f6xQ0g5B4b6DgkzOWzmRPEXTu
    sabhashanki:
      email: test@gmail.com
      id: 62f88833f241ee33f698d895b81c5eff
      logged_in: false
      name: shankesh
      password: $2b$12$YPCeNc397qprTnhI9pXxV.zpxwNT51uvONNKeZoT/.MAEPvVmWmKi
    sabhashankii:
      email: ihave@gmail.com
      id: edba8337ddc986f2c3854f550a75f863
      logged_in: false
      name: shankesh
      password: $2b$12$.xY0iDFhuminsBF5BizNMOplvgztV0mrWEI1Rvx1NIuFwSV8Ij5Tq
    shankesh:
      email: hello@gmail.com
      id: 8d65e32a1c7989ebaf9f83d02011c8c1
      logged_in: false
      name: Shankesh Raju MS
      password: $2b$12$tMEI/n73JIvNEnwDz97wiuBytU3pjpXbRDneVg1W8CVpT6u8lRtvG
preauthorized:
  emails:
  - melsby@gmail.com
